[rospy.client][INFO] 2018-12-05 15:50:25,275: init_node, name[/dashboard_node_onboardpc_10030_1862415346945135911], pid[10052]
[xmlrpc][INFO] 2018-12-05 15:50:25,275: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-12-05 15:50:25,276: Started XML-RPC server [http://onboardpc:37807/]
[rospy.init][INFO] 2018-12-05 15:50:25,276: ROS Slave URI: [http://onboardpc:37807/]
[rospy.impl.masterslave][INFO] 2018-12-05 15:50:25,276: _ready: http://onboardpc:37807/
[xmlrpc][INFO] 2018-12-05 15:50:25,277: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2018-12-05 15:50:25,277: Registering with master node http://localhost:11311
[rospy.init][INFO] 2018-12-05 15:50:25,377: registered with master
[rospy.rosout][INFO] 2018-12-05 15:50:25,377: initializing /rosout core topic
[rospy.rosout][INFO] 2018-12-05 15:50:25,380: connected to core topic /rosout
[rospy.simtime][INFO] 2018-12-05 15:50:25,382: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2018-12-05 15:50:25,700: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2018-12-05 15:50:27,050: topic[/rosout_agg] adding connection to [http://onboardpc:45773/], count 0
[rospy.internal][INFO] 2018-12-05 15:50:27,226: topic[/diagnostics_toplevel_state] adding connection to [http://onboardpc:45539/], count 0
[rospy.internal][INFO] 2018-12-05 15:50:27,568: topic[/dashboard_agg] adding connection to [http://onboardpc:33455/], count 0
[rospy.internal][WARNING] 2018-12-05 16:03:03,459: Unknown error initiating TCP/IP socket to onboardpc:55093 (http://onboardpc:45773/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2018-12-05 16:03:03,460: topic[/rosout_agg] removing connection to http://onboardpc:45773/
[rospy.internal][INFO] 2018-12-05 16:03:03,553: topic[/rosout] removing connection to /rosout
[rospy.internal][WARNING] 2018-12-05 16:03:05,932: Unknown error initiating TCP/IP socket to onboardpc:36963 (http://onboardpc:33455/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2018-12-05 16:03:05,932: topic[/dashboard_agg] removing connection to http://onboardpc:33455/
[rospy.internal][INFO] 2018-12-05 16:03:06,004: topic impl's ref count is zero, deleting topic /diagnostics_toplevel_state...
[rospy.internal][INFO] 2018-12-05 16:03:06,004: topic[/diagnostics_toplevel_state] removing connection to http://onboardpc:45539/
[rosout][WARNING] 2018-12-05 16:03:06,005: unable to communicate with ROS Master, registrations are now out of sync
[rospy.registration][ERROR] 2018-12-05 16:03:06,010: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/registration.py", line 414, in reg_removed
    master.unregisterSubscriber(get_caller_id(), resolved_name, self.uri)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2018-12-05 16:03:06,012: topic impl's ref count is zero, deleting topic /rosout_agg...
[rosout][WARNING] 2018-12-05 16:03:06,013: unable to communicate with ROS Master, registrations are now out of sync
[rospy.registration][ERROR] 2018-12-05 16:03:06,014: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/registration.py", line 414, in reg_removed
    master.unregisterSubscriber(get_caller_id(), resolved_name, self.uri)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2018-12-05 16:03:06,020: topic impl's ref count is zero, deleting topic /dashboard_agg...
[rosout][WARNING] 2018-12-05 16:03:06,021: unable to communicate with ROS Master, registrations are now out of sync
[rospy.registration][ERROR] 2018-12-05 16:03:06,022: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/registration.py", line 414, in reg_removed
    master.unregisterSubscriber(get_caller_id(), resolved_name, self.uri)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[rospy.internal][WARNING] 2018-12-05 16:03:06,103: Unknown error initiating TCP/IP socket to onboardpc:45635 (http://onboardpc:45539/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.core][INFO] 2018-12-05 16:03:06,140: signal_shutdown [atexit]
[rospy.registration][WARNING] 2018-12-05 16:03:06,141: cannot unregister with master due to network issues
[rospy.impl.masterslave][INFO] 2018-12-05 16:03:06,142: atexit
